import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'src/reference-manifest.json'
rows=json.loads(p.read_text())
labels=[
'Credits / license (reference only)', 'UI kit cover (reference only)', 'Splash, onboarding 1', 'Onboarding 2, onboarding 3', 'Sign in', 'Sign in focused keyboard', 'Forgot password', 'Sign up focused phone', 'Verification keyboard', 'Sign up', 'No friends', 'Friends first seen', 'Friends feed', 'Friend search', 'Chat', 'Invite friends', 'Discover people', 'Premium profile', 'Nonmember profile', 'Friend profile', 'Friend action sheet', 'Author detail', 'Membership', 'Book overview', 'Book reviews', 'Write review keyboard', 'Book action sheet', 'Share, save to collection', 'Completed and tip popups', 'Reader, text selection', 'Reader page progress, settings', 'Dark reader, settings', 'Sepia reader, progress', 'Sepia reader settings', 'Reading overview, store book', 'Book purchase options, download', 'Download popup, checkout', 'Payment success and failure', 'Payment methods, App Store', 'Collections, collection detail', 'Add purchased books, My Collections', 'Collection list, delete row', 'New collection, edit collection', 'Collection selected rows, delete popup', 'Empty collections', 'Notifications, empty notifications', 'Profile menu, settings', 'Edit profile, reading goals', 'Goal picker, goal selected popup', 'Home long screen', 'Library long screen', 'Store, search categories', 'Search focused, search results', 'Horror category', 'Dark splash, onboarding 1', 'Dark onboarding 2 and 3', 'Dark sign in, focused keyboard', 'Dark forgot password, sign up', 'Dark phone input, verification', 'Dark no friends, friends first seen', 'Dark friends feed, search', 'Dark chat, invite friends', 'Dark discover people', 'Dark premium and nonmember profiles', 'Dark friend profile and action sheet', 'Dark author and membership', 'Dark book overview and reviews', 'Dark write review and book action sheet', 'Dark share and save collection', 'Dark completion and tip popups', 'Reader and text selection', 'Reader progress and dark settings popover', 'Dark reader and settings', 'Sepia reader, progress, dark settings popover', 'Dark reading overview and purchase options', 'Dark download, completion, checkout', 'Dark payment success, failure, methods', 'App Store checkout preview', 'Dark collections and detail', 'Dark add books and My Collections', 'Dark collection list and remove row', 'Dark new collection and edit', 'Dark selection and delete popup', 'Dark empty collections', 'Dark notifications and empty state', 'Dark profile menu and settings', 'Dark edit profile and reading goals', 'Dark goal picker and completion', 'Dark Home long screen', 'Dark Library long screen', 'Dark Store', 'Dark Search categories', 'Dark Search keyboard', 'Dark Search results', 'Dark Horror category'
]
assert len(labels)==len(rows)==95
for row,label in zip(rows,labels): row['reference_states']=label
p.write_text(json.dumps(rows,indent=2)+'\n')
