from pathlib import Path
p=Path('src/ui.tsx');s=p.read_text().replace('import { Ionicons } from "@expo/vector-icons";','import { AppSymbol } from "./symbols";\nimport { LinearGradient } from "expo-linear-gradient";\nimport * as Haptics from "expo-haptics";')
s=s.replace('bg: dark ? "#111111" : "#FFFFFF"','bg: dark ? "#101117" : "#F8F7FC"').replace('card: dark ? "#282828" : "#F5F5F8"','card: dark ? "#20212B" : "#EFEDF6"').replace('ink: dark ? "#E4E2EB" : "#41414F"','ink: dark ? "#F1F0F8" : "#252332"').replace('muted: dark ? "#9995A6" : "#9C99AA"','muted: dark ? "#A7A5B6" : "#777486"').replace('heading: dark ? purple : "#41414F"','heading: dark ? "#F1F0F8" : "#252332"')
s=s.replace('fontFamily: bold ? "Poppins_600SemiBold" : "Poppins_400Regular",','fontFamily: Platform.OS === "web" ? "-apple-system, BlinkMacSystemFont, Inter, system-ui, sans-serif" : undefined,\n          fontWeight: bold ? "600" : "400",\n          letterSpacing: size >= 24 ? -0.8 : 0,')
s=s.replace('return <Ionicons name={name} size={size} color={color} />;','return <AppSymbol name={name} size={size} color={color} />;')
s=s.replace('onPress={onPress}\n        onPressIn','onPress={(event) => { if(Platform.OS !== "web") void Haptics.selectionAsync().catch(()=>{}); onPress?.(event); }}\n        onPressIn')
s=s.replace('fontFamily: "Poppins_400Regular",','fontFamily: Platform.OS === "web" ? "system-ui" : undefined,')
s=s.replace('backgroundColor: t.dark ? "#282828E8" : "#FFFFFFE8"','backgroundColor: t.dark ? "#242430AA" : "#FFFFFFAA"')
start=s.index('export function Avatar(');end=s.index('export function BookRow(',start)
s=s[:start]+'''export function Avatar({index=0,size=46,ring=false,name="",source}:any){const colors = [["#DCD4FF","#9F8BEE"],["#D4E8EE","#77A6AE"],["#F7DDCE","#DCAB87"]] as const;return <LinearGradient colors={colors[index%3]} style={{width:size,height:size,borderRadius:size/2,alignItems:'center',justifyContent:'center',borderWidth:ring?3:1,borderColor:'#FFFFFF88'}}>{name?<Txt size={size*.34} bold color="#48405F">{name.split(' ').map((x:string)=>x[0]).slice(0,2).join('').toUpperCase()}</Txt>:<AppSymbol name="person" color="#655884" size={size*.43}/>}</LinearGradient>}\n'''+s[end:]
start=s.index('export function BookCover(');end=s.index('export function Card(',start)
s=s[:start]+'''export function BookCover({book,large=false,width:custom}:any){const width=custom||(large?188:82),height=width*1.43;return <View style={{width,height,borderRadius:12,overflow:'hidden',backgroundColor:'#332745',borderLeftWidth:3,borderLeftColor:'#FFFFFF40'}}><Image source={book.image||art[book.id as keyof typeof art]||art.ocean} style={StyleSheet.absoluteFill}/><LinearGradient colors={['#080B1800','#080B1820','#080B18DF']} style={{...StyleSheet.absoluteFillObject,justifyContent:'flex-end',padding:width*.09}}><Txt color="white" size={large||custom?Math.max(14,width*.115):10} bold numberOfLines={3}>{book.title}</Txt>{(large||custom)&&<Txt color="#FFFFFFBB" size={10} style={{marginTop:7}}>{book.author}</Txt>}</LinearGradient></View>}\n'''+s[end:]
start=s.index('export function Art(');end=s.index('export function FloatArt(',start)
s=s[:start]+'''export function Art({name,size=200,style}:any){const icon=({logo:'book',empty:'folder-open',check:'checkmark-circle',bulb:'sparkles',coffee:'leaf',bell:'notifications',trash:'trash',timer:'timer',trophy:'trophy',orbit:'people'} as any)[name]||'sparkles';return <View style={[{width:size,height:size,alignSelf:'center',alignItems:'center',justifyContent:'center'},style]}><LinearGradient colors={['#ECE7FF','#C5B5F5','#8970DC']} style={{width:size*.72,height:size*.72,borderRadius:size*.25,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:'#FFFFFFCC',transform:[{rotate:'-8deg'}]}}><AppSymbol name={icon} color="white" size={size*.36} animated/></LinearGradient></View>}\n'''+s[end:]
p.write_text(s)
