import React from "react";
import { Platform } from "react-native";
import { SymbolView } from "expo-symbols";
import {
  House,
  BookOpen,
  Book,
  Search,
  ShoppingBag,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  Plus,
  Check,
  CheckCircle2,
  Circle,
  Heart,
  Bookmark,
  Share2,
  MoreHorizontal,
  MoreVertical,
  Settings2,
  Bell,
  MessageCircle,
  Users,
  User,
  UserPlus,
  Trash2,
  Folder,
  FolderOpen,
  Play,
  PlayCircle,
  Pause,
  Video,
  Eye,
  EyeOff,
  Mail,
  LockKeyhole,
  ShieldCheck,
  Sun,
  Moon,
  Sparkles,
  Timer,
  Trophy,
  Flame,
  Gift,
  HelpCircle,
  LogOut,
  Download,
  Upload,
  Volume2,
  VolumeX,
  Flag,
  RefreshCw,
  X,
  PenLine,
  Send,
  SlidersHorizontal,
  Compass,
  Leaf,
  Headphones,
  Star,
  LayoutGrid,
  Calendar,
  Globe,
  Target,
} from "lucide-react-native";
const table: Record<string, [string, any]> = {
  home: ["house", House],
  book: ["book", BookOpen],
  library: ["books.vertical", Book],
  search: ["magnifyingglass", Search],
  bag: ["bag", ShoppingBag],
  "chevron-back": ["chevron.left", ChevronLeft],
  "chevron-forward": ["chevron.right", ChevronRight],
  "arrow-forward": ["arrow.right", ArrowRight],
  add: ["plus", Plus],
  checkmark: ["checkmark", Check],
  "checkmark-circle": ["checkmark.circle.fill", CheckCircle2],
  ellipse: ["circle", Circle],
  heart: ["heart", Heart],
  bookmark: ["bookmark", Bookmark],
  share: ["square.and.arrow.up", Share2],
  "share-social": ["square.and.arrow.up", Share2],
  "ellipsis-horizontal": ["ellipsis", MoreHorizontal],
  "ellipsis-vertical": ["ellipsis", MoreVertical],
  settings: ["slider.horizontal.3", Settings2],
  notifications: ["bell", Bell],
  chatbubble: ["bubble.left", MessageCircle],
  "chatbubble-ellipses": ["bubble.left.and.bubble.right", MessageCircle],
  chatbox: ["text.bubble", MessageCircle],
  people: ["person.2", Users],
  person: ["person", User],
  "person-add": ["person.badge.plus", UserPlus],
  trash: ["trash", Trash2],
  folder: ["folder", Folder],
  "folder-open": ["folder", FolderOpen],
  play: ["play.fill", Play],
  "play-circle": ["play.circle.fill", PlayCircle],
  pause: ["pause.fill", Pause],
  videocam: ["video", Video],
  eye: ["eye", Eye],
  "eye-off": ["eye.slash", EyeOff],
  mail: ["envelope", Mail],
  lock: ["lock", LockKeyhole],
  "shield-checkmark": ["checkmark.shield", ShieldCheck],
  sunny: ["sun.max", Sun],
  moon: ["moon", Moon],
  sparkles: ["sparkles", Sparkles],
  timer: ["timer", Timer],
  trophy: ["trophy", Trophy],
  flame: ["flame", Flame],
  gift: ["gift", Gift],
  "help-circle": ["questionmark.circle", HelpCircle],
  "log-out": ["rectangle.portrait.and.arrow.right", LogOut],
  download: ["arrow.down.circle", Download],
  upload: ["arrow.up.circle", Upload],
  "volume-high": ["speaker.wave.2", Volume2],
  "volume-mute": ["speaker.slash", VolumeX],
  flag: ["flag", Flag],
  refresh: ["arrow.clockwise", RefreshCw],
  close: ["xmark", X],
  create: ["square.and.pencil", PenLine],
  "paper-plane": ["paperplane", Send],
  options: ["slider.horizontal.3", SlidersHorizontal],
  compass: ["safari", Compass],
  leaf: ["leaf", Leaf],
  headset: ["headphones", Headphones],
  star: ["star", Star],
  grid: ["square.grid.2x2", LayoutGrid],
  calendar: ["calendar", Calendar],
  globe: ["globe", Globe],
  target: ["target", Target],
};
export function AppSymbol({
  name = "chevron-back",
  size = 23,
  color = "#7055E8",
  animated = false,
}: any) {
  const key = name.replace(/-outline$/, "");
  const [sf, Vector] = table[key] || ["sparkles", Sparkles];
  return Platform.OS === "ios" ? (
    <SymbolView
      name={sf as any}
      size={size}
      style={{ width: size, height: size }}
      tintColor={color}
      type="hierarchical"
      weight="medium"
      animationSpec={
        animated ? { effect: { type: "bounce" }, repeatCount: 1 } : undefined
      }
    />
  ) : (
    <Vector size={size} color={color} strokeWidth={1.7} />
  );
}
